# Source: jx-pipelines-visualizer/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-pipelines-visualizer
  labels:
    app.kubernetes.io/name: jx-pipelines-visualizer
    app.kubernetes.io/instance: "jx-pipelines-visualizer"
    helm.sh/chart: jx-pipelines-visualizer-1.7.5
    app.kubernetes.io/version: "1.7.5"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::971057899310:role/tf-jx-famous-lioness-jx-pipelines-visualizer
    meta.helm.sh/release-name: 'jx-pipelines-visualizer'
  namespace: jx
