# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "dev"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/vnemane/jx3-eks-vault.git
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: "Never"
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: https://jenkins-x-charts.github.io/repo
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: ""
    envOrganisation: todo
    gitServer: https://github.com
    kubeProvider: "eks"
    pipelineUsername: "virajnemane"
    pipelineUserEmail: "jenkins-x@googlegroups.com"
    prowConfig: Scheduler
    storageLocations:
      - bucketUrl: "s3://logs-tf-jx-famous-lioness-20220301061203603900000007"
        classifier: "logs"
      - bucketUrl: "s3://reports-tf-jx-famous-lioness-20220301061203601000000005"
        classifier: "reports"
      - bucketUrl: "s3://repository-tf-jx-famous-lioness-20220301061203593500000004"
        classifier: "repository"
