filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.174.129.120.12.nip.io
releases:
- chart: dev/gohttpaws
  version: 0.0.1
  name: gohttpaws
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
